### ISSUE TITLE
[bug] `documentSelector` does not support `ts` scripts

### ISSUE THREAD

**Issue by BachiMjavanadze** [htmlhint/vscode-htmlhint#152]
This is my configuration in `settings.json`:

```json
"htmlhint.documentSelector": [
  "html",
  "ts"
]
```

but actually extension does not support linting in `*.ts` scripts.

desired behavior:

![image](https://github.com/htmlhint/vscode-htmlhint/assets/38082501/04770803-d24d-4616-96ce-2f2f5b10d91c)

**Comment by coliff** [comment]
Hi - I've tested that this works as expected... you need this config though:

```json
{
  "htmlhint.documentSelector": ["html", "typescript"]
}
```

basically you have to use the name of the language, not just the file extension... so it's markdown (and not md)

**Comment by BachiMjavanadze** [comment]
@coliff Thanks!

**Comment by BachiMjavanadze** [comment]
@coliff but may be it is possible to move error indicator (yellow line) close to tag

![image](https://github.com/htmlhint/vscode-htmlhint/assets/38082501/899de5f9-05b8-48ad-b2fa-dad41af4cdd7)
