### ISSUE TITLE
Make it easy to ignore rules on individual pages

### ISSUE THREAD

**Issue by rsgranne** [htmlhint/vscode-htmlhint#164]
It would be absolutely lovely if we could ignore rules on specific pages. 

For instance, my students are including a file named `footer.html` in another file. `footer.html` doesn’t have a DTD at the top, but htmlhint complains about that. I don’t want to disable requiring a doctype globally, only on `footer.html`. 

If there was some way I could use a comment to tell htmlhint to ignore `doctype-first` on `footer.html`, that would be really helpful.

Thank you!

**Comment by coliff** [comment]
Although we don't have that functionality exactly, you can use a custom HTMLHint config in your templates directory with rules customized to work with template partials (for your footers, navs etc) and then a different full HTMLHint for your output/dist folder. That way you could run HTMLHint on your templates and the full final site. I know it's not exactly what you asked for, but that's what I've been doing and it works well. :-)

There are no plans to add such functionality to this plugin directly, I think such a change would be done in the main HTMLHint project.
