### ISSUE TITLE
Two questions i dont have clear

### ISSUE THREAD

**Issue by ejgutierrez74** [htmlhint/vscode-htmlhint#165]
1 - When you pass HTMLHint to a HTML file, you pass or is the same as ww3c validator ?
https://validator.w3.org/ and https://www.w3.org/developers/tools/
Or HTMLHint only tests a file with rules accorded by some developers with html experience...any organitzation or standard is backing HTMLHint ??

2 - Also works for CSS files ? Any similar tool to help to develop CSS files like validator does ?
https://jigsaw.w3.org/css-validator/#validate_by_input

Thanks

**Comment by coliff** [comment]
1. The rules are different to the ww3c validator. This isn't a strict HTML validity checker... but it does check many things which the ww3c validator does not.

2. No, it doesn't work with CSS files. I'd recommend using [Stylelint](https://stylelint.io/) for checking CSS files.

Hope that helps - Happy linting!

**Comment by ejgutierrez74** [comment]
Sorry, but which is then the point with HTMLHint, as said before a group of developers validating some general or standard rules ?  As i understood no www3 or organization behind...so its a general good practice rules...and suppose the same in Stylelint.

Tahnks

**Comment by coliff** [comment]
Yes, HTMLHint isn't associated with any other organization at all. The rules in HTMLHint cover best practises, but also accessibility, performance and opinionated formatting and styling.

**Comment by ejgutierrez74** [comment]
Thanks thats more clear.
