### ISSUE TITLE
Verify domain for VS Code Extension Marketplace

### ISSUE THREAD

**Issue by coliff** [htmlhint/vscode-htmlhint#59]
We can verify the htmlhint.com domain name at: https://marketplace.visualstudio.com/manage/publishers/htmlhint so that users know our extension is official and can be trusted.

It'll appear a bit like this:

![verified-publishers](https://user-images.githubusercontent.com/1212885/191395187-56387838-fcc2-46b1-aadb-3b039f852674.png)

Learn more about verifying ownership here:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

@thedaviddias has access to the domain name records and is the owner of the account so only he can do that.

**Comment by isidorn** [comment]
VS Code PM here,

Great idea, I just wanted to create an issue for this 👏

**Comment by coliff** [comment]
thanks for the quick response on the extension redirect request Isidor! :-) 

@thedaviddias - lets get this setup!

**Comment by thedaviddias** [comment]
Done, in progress!

![CleanShot 2022-10-04 at 18 19 13](https://user-images.githubusercontent.com/237229/193940625-9f4f96ef-1128-4fa9-9d8c-9c4976cb1797.jpg)

**Comment by isidorn** [comment]
Should take a couple of days, if it is longer than that feel free to ping me here and I can reach out to the Marketplace team.

**Comment by coliff** [comment]
Verified now!

![image](https://user-images.githubusercontent.com/1212885/194861531-41bd1c9f-1202-4cee-8efd-f60ee318d305.png)

Thanks both! 🥇
