### ISSUE TITLE
Publish the extension to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [htmlhint/vscode-htmlhint#67]
Hi there to the HTMLHint team 👋!

I would like to ask you to please publish this extension to the [Open VSX marketplace](https://open-vsx.org/).

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

If there are any issues with publishing, I'd be more than happy to help guide through the process or solve any issues that may arise.

**Comment by coliff** [comment]
Coincidental timing! I was going to post an issue about this today after reading about the Open VSX marketplace earlier today.

I'll look into getting this published tomorrow and will update this when I have news to share.

**Comment by robole** [comment]
Hi @coliff 

I use the [publish-vscode-extension GitHub Action](https://github.com/HaaLeo/publish-vscode-extension) to automatically publish my extensions to the VS Code Marketplace and Open VSX marketplace whenever I commit to the main branch. You can look at [File Bunny](https://github.com/robole/vscode-file-bunny) as an example. 

Thanks for your work!

**Comment by robole** [comment]
hi @coliff ,

I understand, no worries.

 I would offer to do it for you, but it requires setting up secrets on the GitHub repo. 

I am not sure what you mean about creating an Oracle account? For [publish to open-vsx,](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) you create an eclipse account. The process is similar to publishing to Microsoft's Marketplace, but is a lot more straightforward. 

To test it, you only need to check that it shows up the marketplace. You do not need to install VSCodium at all.

Best wishes,

Rob

**Comment by mrhyperbit** [comment]
Any Update?

**Comment by coliff** [comment]
Ok, I think it's done! Can you please give this a try and let me know if it works as expected?

https://open-vsx.org/extension/htmlhint/vscode-htmlhint

**Comment by filiptronicek** [comment]
Thank you so much, @coliff, everything looks published correctly 🎉
